apiVersion: v1
kind: Pod
metadata:
  name: memory-test-app
  namespace: test
spec:
  containers:
  - name: memory-app
    image: polinux/stress
    resources:
      limits:
        memory: "120Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]    
    args: [ "--vm", "1", "--vm-bytes", "100M","--vm-hang","1"]



    