apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: demo-voting-app
    name: postgres-pod
spec:
  containers:
  - name: postgres-app
    image: postgres
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"  