apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: demo-voting-app
    name: redis-pod
spec:
  containers:
  - name: redis-app
    image: redis
    ports:
    - containerPort: 6379