apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      name: nginx
      labels:
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80